[package]
name = "kernel"
version = "0.1.0"
authors = ["Marco Cicognani <marco.cicognani@btstore.com>"]
edition = "2018"
build = "build.rs"

##
# Kernel Crates
##

[dependencies.hal]
path = "hal"

##
# External Crates
##

[dependencies.log]
version = "0.4.14"

[dependencies.bit_field]
version = "0.10.1"

##
# External x86_64 Crates
##

[target.'cfg(target_arch = "x86_64")'.dependencies.bootloader]
version = "0.9.16"
features = ["map_physical_memory"]

##
# MeetiX Libraries Crates
##

[dependencies.api]
path = "../lib/api"
features = ["enable_kernel_methods"]

[dependencies.heap]
path = "../lib/heap"
features = ["disable_locked"]

[dependencies.sync]
path = "../lib/sync"

##
# Package Options
##

[package.metadata.bootimage]
run-command = [
    "qemu-system-x86_64.exe.lnk",
    "-m", "64M",
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04",
    "-serial", "stdio",
    "-drive", "format=raw,file={}"
]
#run-args = ["-m", "64M", "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "stdio"]

##
# x86_64 Package Options
##

[package.metadata.bootloader]
# NOTE keep the following virtual addresses aligned with src/mem/layout.rs
physical-memory-offset = "0xffffff7ff8000000"
kernel-stack-address   = "0xfffffffff9e00000"
kernel-stack-size = 511