[workspace]
members = [
    # Kernel Crates
    "src/kernel",
    "src/kernel/hh_loader",
    "src/kernel/libs/hal",
    "src/kernel/libs/logger",
    # Library Crates
    "src/libs/api",
    "src/libs/heap",
    "src/libs/macros",
    "src/libs/os",
    "src/libs/sync",
    # App Crates
    "src/userland/apps/example_app",
    # Binary Crates
    "src/userland/bins/example"

]
