[workspace]
members = [
    # Kernel Crates
    "Kernel",
    "Kernel/HHLoader",
    "Kernel/SharedCode",
    # Userland/Kernel Libraries
    "UKLibs/LibApi",
    "UKLibs/LibApiData",
    "UKLibs/LibBits",
    "UKLibs/LibHeap",
    "UKLibs/LibHelps",
    "UKLibs/LibOS",
    "UKLibs/LibSymbols",
    "UKLibs/LibSync",
    # Userland Libraries
    "Userland/UsrLibs/LibApi",
    # App Crates
    "Userland/Apps/ExampleApp",
    # Binary Crates
    "Userland/Bins/Example",
]
