[workspace]
members = [
    # Kernel Crates
    "kernel",
    "kernel/hh_loader",
    "kernel/shared",
    # Library Crates
    "libs/api",
    "libs/heap",
    "libs/macros",
    "libs/os",
    "libs/sync",
    # App Crates
    "userland/apps/example_app",
    # Binary Crates
    "userland/bins/example",
]
