[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
rustflags = "-Z macro-backtrace"
target = "src/targets/x86_64-meetix.json"

[target.'cfg(target_os = "meetixos")']
runner = "bootimage runner"