[package]
name = "hh_loader"
version = "0.1.0"
edition = "2018"

##
# Kernel Crates
##

[dependencies.hal]
path = "../hal"

##
# External Crates
##

[dependencies.log]
version = "0.4.14"

##
# MeetiX Libraries Crates
##

[dependencies.sync]
path = "../../lib/sync"