[package]
name = "symbols"
version = "0.1.0"
edition = "2018"
authors = ["Marco Cicognani <marco.cicognani@meetixos.org>"]

[dependencies]
# ------------------------------ MeetiX Libraries Crates ------------------------------- #
helps = { path = "../LibHelps" }